[settings]
asdf_compat = true
auto_install = true
github_attestations = false
experimental = true

[settings.aqua]
cosign = false
slsa = false
minisign = false
github_attestations = false

[settings.github]
github_attestations = false
